{
 "title": "Flashblock - Classic Builder",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Payloads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Payloads Built",
   "type": "stat",
   "description": "Number of payload jobs that have produced a block payload successfully.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_classic_payloads_jobs_completed",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Time",
   "type": "stat",
   "description": "Time given to the builder to build a payload (block time).",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_classic_payloads_job_deadline",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Number",
   "type": "stat",
   "description": "Latest built payload block number",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_classic_payloads_block_number",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gas Per Second",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(reth_classic_payloads_gas_used_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions Built",
   "type": "stat",
   "description": "The total number of all transactions built across all payload jobs.",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_classic_payloads_tx_count_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Gas Built",
   "type": "stat",
   "description": "The sum of all gas consumed by all transactions built across all payload jobs.",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_classic_payloads_gas_used_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Blob Gas Built",
   "type": "stat",
   "description": "Total blob gas used by all blob transactions in all produced payloads.",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_classic_payloads_blob_gas_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Fees",
   "type": "stat",
   "description": "Total fees accumulated by all produced payloads.",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_classic_payloads_fees_total / 1e18",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_classic_payloads_jobs_failed",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions Per Payload",
   "type": "timeseries",
   "description": "Number of transactions in a produced payload.",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "reth_classic_payloads_tx_count_histogram{quantile=\"0.95\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Payload Jobs Success Rate",
   "type": "timeseries",
   "description": "Percentage of Payload Jobs that ended in successfully built payload.",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "reth_classic_payloads_jobs_completed / (reth_classic_payloads_jobs_failed + reth_classic_payloads_jobs_completed)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gas per Payload",
   "type": "timeseries",
   "description": "Amount of gas used by transactions in a produced payload.",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "reth_classic_payloads_gas_used_histogram{quantile=\"0.95\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Payload Job Duration",
   "type": "timeseries",
   "description": "Duration of a payload job from start to completion or failure.",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_classic_pipeline_exec_duration_histogram{quantile=\"0.95\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "reth_classic_payloads_job_deadline",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Payload Gas Utilization",
   "type": "timeseries",
   "description": "The percentage of gas utilized by transactions in a produced payload.",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "reth_classic_payloads_gas_utilized{quantile=\"0.95\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fees per Payload (ETH)",
   "type": "timeseries",
   "description": "Fees paid by transactions in produced payloads",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 11 },
   "targets": [
    {
     "expr": "reth_classic_payloads_fees_histogram{quantile=\"0.95\"} / 1e18",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Classic Builder Pipeline (real-time)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "Pipeline Steps Execution Stats",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_classic_step_p_exec_duration_per_job{quantile=\"0.95\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "reth_classic_step_1_1_exec_duration_per_job{quantile=\"0.95\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "reth_classic_step_1_2_exec_duration_per_job{quantile=\"0.95\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "reth_classic_step_1_3_exec_duration_per_job{quantile=\"0.95\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "reth_classic_step_1_1_invoked_per_job{quantile=\"0.95\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipeline Steps Execution Time",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_classic_step_1_1_exec_duration_per_job{quantile=\"0.95\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "reth_classic_step_1_2_exec_duration_per_job{quantile=\"0.95\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "reth_classic_step_1_3_exec_duration_per_job{quantile=\"0.95\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "reth_classic_step_p_exec_duration_per_job{quantile=\"0.95\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AppendOrders Step Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_classic_step_1_1_exec_duration_histogram{quantile=\"0.95\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AppendOrders Per Job Exec Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_classic_step_1_1_exec_duration_per_job{quantile=\"0.95\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OrderByPriorityFee Step Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_classic_step_1_2_exec_duration_histogram{quantile=\"0.95\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OrderByPriorityFee Per Job Exec Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_classic_step_1_2_exec_duration_per_job{quantile=\"0.95\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BuilderEpilogue Exec Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_classic_step_e_exec_duration_histogram{quantile=\"0.95\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RemoveRevertedTransactions Exec Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_classic_step_1_3_exec_duration_histogram{quantile=\"0.95\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OptimismPrologue Step Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_classic_step_p_exec_duration_histogram{quantile=\"0.95\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OptimismPrologue Per Job Exec Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_classic_step_p_exec_duration_per_job{quantile=\"0.95\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Revert Protection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Total Dropped Transactions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_classic_step_1_3_txs_dropped_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Dropped Gas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_classic_step_1_3_gas_dropped_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dropped Transactions Per Payload",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "reth_classic_step_1_3_txs_dropped_per_job{quantile=\"0.95\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dropped Gas Per Payload",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "reth_classic_step_1_3_gas_dropped_per_job{quantile=\"0.95\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Drop rate per payload",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "reth_classic_step_1_3_txs_dropped_per_job{quantile=\"0.95\"} / reth_classic_step_1_1_per_job_txs_included{quantile=\"0.95\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC (Cumulative)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "engine_forkchoiceUpdated",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "expr": "reth_engine_rpc_forkchoice_updated_messages",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "engine_newPayloadV3",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 7, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "expr": "reth_engine_rpc_new_payload_v3_count",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "engine_getPayloadV3",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "expr": "reth_engine_rpc_get_payload_v3_count",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}